package com.cloud.carads.system.sms.entity;

import java.util.Date;

public class SmsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.id
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.phone_no
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.content
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.from_ip
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private String fromIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.return_value
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private String returnValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.receiver_time
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private Date receiverTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.response_time
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private Date responseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.channel
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sms_log.status
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.id
     *
     * @return the value of t_sms_log.id
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.id
     *
     * @param id the value for t_sms_log.id
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.phone_no
     *
     * @return the value of t_sms_log.phone_no
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.phone_no
     *
     * @param phoneNo the value for t_sms_log.phone_no
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.content
     *
     * @return the value of t_sms_log.content
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.content
     *
     * @param content the value for t_sms_log.content
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.from_ip
     *
     * @return the value of t_sms_log.from_ip
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.from_ip
     *
     * @param fromIp the value for t_sms_log.from_ip
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.return_value
     *
     * @return the value of t_sms_log.return_value
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public String getReturnValue() {
        return returnValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.return_value
     *
     * @param returnValue the value for t_sms_log.return_value
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setReturnValue(String returnValue) {
        this.returnValue = returnValue == null ? null : returnValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.receiver_time
     *
     * @return the value of t_sms_log.receiver_time
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public Date getReceiverTime() {
        return receiverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.receiver_time
     *
     * @param receiverTime the value for t_sms_log.receiver_time
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setReceiverTime(Date receiverTime) {
        this.receiverTime = receiverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.response_time
     *
     * @return the value of t_sms_log.response_time
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public Date getResponseTime() {
        return responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.response_time
     *
     * @param responseTime the value for t_sms_log.response_time
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setResponseTime(Date responseTime) {
        this.responseTime = responseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.channel
     *
     * @return the value of t_sms_log.channel
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.channel
     *
     * @param channel the value for t_sms_log.channel
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sms_log.status
     *
     * @return the value of t_sms_log.status
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sms_log.status
     *
     * @param status the value for t_sms_log.status
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SmsLog other = (SmsLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getPhoneNo() == null ? other.getPhoneNo() == null : this.getPhoneNo().equals(other.getPhoneNo()))
                && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()))
                && (this.getFromIp() == null ? other.getFromIp() == null : this.getFromIp().equals(other.getFromIp()))
                && (this.getReturnValue() == null ? other.getReturnValue() == null : this.getReturnValue().equals(other.getReturnValue()))
                && (this.getReceiverTime() == null ? other.getReceiverTime() == null : this.getReceiverTime().equals(other.getReceiverTime()))
                && (this.getResponseTime() == null ? other.getResponseTime() == null : this.getResponseTime().equals(other.getResponseTime()))
                && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
                && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPhoneNo() == null) ? 0 : getPhoneNo().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        result = prime * result + ((getFromIp() == null) ? 0 : getFromIp().hashCode());
        result = prime * result + ((getReturnValue() == null) ? 0 : getReturnValue().hashCode());
        result = prime * result + ((getReceiverTime() == null) ? 0 : getReceiverTime().hashCode());
        result = prime * result + ((getResponseTime() == null) ? 0 : getResponseTime().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", content=").append(content);
        sb.append(", fromIp=").append(fromIp);
        sb.append(", returnValue=").append(returnValue);
        sb.append(", receiverTime=").append(receiverTime);
        sb.append(", responseTime=").append(responseTime);
        sb.append(", channel=").append(channel);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}