package com.cloud.carads.management.entity;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

@ApiModel(description = "车主信息表，不包含验证码字段")
public class CAccountInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.id
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车主id，后台自动生成，完善信息时必输，注册时非必输", example = "1", position = 1)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.user_name
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "用户名，注册时必输", example = "zhangqw", position = 2, required = true)
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.password
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "密码,注册时必输", example = "a123456", position = 3)
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.father_id
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "推荐人id,车主注册时输入推荐人用户名，调用后台接口判断用户是否存在如果存在则返回该用户的id", example = "111", position = 4)
    private Long fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.grand_id
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "传0")
    private Long grandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.ggrand_id
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "传0")
    private Long ggrandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.mobile_no
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "手机号,注册时必输", example = "15951903466", position = 5)
    private String mobileNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.identity_card
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "身份证图片地址", example = "http://oss.aliyun.com/temo.gif", position = 6)
    private String identityCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.driving_card
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "行驶证图片地址", example = "http://oss.aliyun.com/temo.gif", position = 7)
    private String drivingCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.car_side_img
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车辆侧面图片地址", example = "http://oss.aliyun.com/temo.gif", position = 8)
    private String carSideImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.car_header_img
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车辆头部图片地址", example = "http://oss.aliyun.com/temo.gif", position = 9)
    private String carHeaderImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.real_name
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "真实姓名", example = "王东方", position = 10)
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.identity_no
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "身份证号", example = "322410211212121021", position = 11)
    private String identityNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.borth_date
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "出生日期", example = "2018-01-02", position = 12)
    private String borthDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.plate_no
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车牌号", example = "浙B0101D", position = 13)
    private String plateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.detail_address
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "详细地址", example = "熙春路3号春江新村3栋三单元302", position = 14)
    private String detailAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.province
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "省", example = "浙江省", position = 15)
    private String province;

    @ApiModelProperty(value = "车辆视频", example = "http://video.yeah.com/test.mp4", position = 36)
    private String carVideo;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.city
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "市", example = "杭州市", position = 16)
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.area
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "区", example = "余杭区", position = 17)
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.province_code
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "省编码", example = "330000", position = 18)
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.city_code
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "市编码", example = "330100", position = 19)
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.area_code
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "区编码", example = "330110", position = 20)
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.old_address
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "原地址", example = "江苏省南京市玄武区玄武大道11号樱铁村3栋2单元101", position = 21)
    private String oldAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.village
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "小区，用户输入小区名称调用百度地图模糊查询小区然后用户选择具体的小区", example = "奥体花园", position = 22)
    private String village;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.car_brand
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车辆品牌,查询数据字典 传值T_CAR_BRAND", example = "AODI_CAR", position = 23)
    private String carBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.car_model
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "查询数据字典  例如上面选择时AODI_CAR 传值AODI_CAR", example = "A4", position = 24)
    private String carModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.sex
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "性别，1男 0女", example = "0", position = 25)
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.bank_car_no
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "银行卡号", example = "62260210202416201", position = 26)
    private String bankCarNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.open_bank
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "开户行，数据字典T_BANK_CODE", example = "BANK_ICBC", position = 27)
    private String openBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.info_from
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "信息来源，数据字典C_INFO_FROM", example = "COMMUNITY_ADS", position = 28)
    private String infoFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.net_car
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "是否为网约车1是0否", example = "1", position = 29)
    private Integer netCar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.flag
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "审核状态，0待审核 1审核通过2审核未通过 5已删除 9草稿未完善信息", example = "0", position = 30)
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.create_time
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "当前时间或者不用传值")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.update_time
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "当前时间或者不用传值")
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.lgt
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车主所在小区经度", example = "12.33101", position = 31)
    private Double lgt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_account_info.lat
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @ApiModelProperty(value = "车主所在小区纬度", example = "112.43101", position = 32)
    private Double lat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.id
     *
     * @return the value of c_account_info.id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.id
     *
     * @param id the value for c_account_info.id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.user_name
     *
     * @return the value of c_account_info.user_name
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.user_name
     *
     * @param userName the value for c_account_info.user_name
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.password
     *
     * @return the value of c_account_info.password
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.password
     *
     * @param password the value for c_account_info.password
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.father_id
     *
     * @return the value of c_account_info.father_id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Long getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.father_id
     *
     * @param fatherId the value for c_account_info.father_id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setFatherId(Long fatherId) {
        this.fatherId = fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.grand_id
     *
     * @return the value of c_account_info.grand_id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Long getGrandId() {
        return grandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.grand_id
     *
     * @param grandId the value for c_account_info.grand_id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setGrandId(Long grandId) {
        this.grandId = grandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.ggrand_id
     *
     * @return the value of c_account_info.ggrand_id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Long getGgrandId() {
        return ggrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.ggrand_id
     *
     * @param ggrandId the value for c_account_info.ggrand_id
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setGgrandId(Long ggrandId) {
        this.ggrandId = ggrandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.mobile_no
     *
     * @return the value of c_account_info.mobile_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.mobile_no
     *
     * @param mobileNo the value for c_account_info.mobile_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.identity_card
     *
     * @return the value of c_account_info.identity_card
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getIdentityCard() {
        return identityCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.identity_card
     *
     * @param identityCard the value for c_account_info.identity_card
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setIdentityCard(String identityCard) {
        this.identityCard = identityCard == null ? null : identityCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.driving_card
     *
     * @return the value of c_account_info.driving_card
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getDrivingCard() {
        return drivingCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.driving_card
     *
     * @param drivingCard the value for c_account_info.driving_card
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setDrivingCard(String drivingCard) {
        this.drivingCard = drivingCard == null ? null : drivingCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.car_side_img
     *
     * @return the value of c_account_info.car_side_img
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getCarSideImg() {
        return carSideImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.car_side_img
     *
     * @param carSideImg the value for c_account_info.car_side_img
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCarSideImg(String carSideImg) {
        this.carSideImg = carSideImg == null ? null : carSideImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.car_header_img
     *
     * @return the value of c_account_info.car_header_img
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getCarHeaderImg() {
        return carHeaderImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.car_header_img
     *
     * @param carHeaderImg the value for c_account_info.car_header_img
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCarHeaderImg(String carHeaderImg) {
        this.carHeaderImg = carHeaderImg == null ? null : carHeaderImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.real_name
     *
     * @return the value of c_account_info.real_name
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.real_name
     *
     * @param realName the value for c_account_info.real_name
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.identity_no
     *
     * @return the value of c_account_info.identity_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getIdentityNo() {
        return identityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.identity_no
     *
     * @param identityNo the value for c_account_info.identity_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setIdentityNo(String identityNo) {
        this.identityNo = identityNo == null ? null : identityNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.borth_date
     *
     * @return the value of c_account_info.borth_date
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getBorthDate() {
        return borthDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.borth_date
     *
     * @param borthDate the value for c_account_info.borth_date
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setBorthDate(String borthDate) {
        this.borthDate = borthDate == null ? null : borthDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.plate_no
     *
     * @return the value of c_account_info.plate_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getPlateNo() {
        return plateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.plate_no
     *
     * @param plateNo the value for c_account_info.plate_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setPlateNo(String plateNo) {
        this.plateNo = plateNo == null ? null : plateNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.detail_address
     *
     * @return the value of c_account_info.detail_address
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getDetailAddress() {
        return detailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.detail_address
     *
     * @param detailAddress the value for c_account_info.detail_address
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress == null ? null : detailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.province
     *
     * @return the value of c_account_info.province
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.province
     *
     * @param province the value for c_account_info.province
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.city
     *
     * @return the value of c_account_info.city
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.city
     *
     * @param city the value for c_account_info.city
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.area
     *
     * @return the value of c_account_info.area
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.area
     *
     * @param area the value for c_account_info.area
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.province_code
     *
     * @return the value of c_account_info.province_code
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.province_code
     *
     * @param provinceCode the value for c_account_info.province_code
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.city_code
     *
     * @return the value of c_account_info.city_code
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.city_code
     *
     * @param cityCode the value for c_account_info.city_code
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.area_code
     *
     * @return the value of c_account_info.area_code
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.area_code
     *
     * @param areaCode the value for c_account_info.area_code
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.old_address
     *
     * @return the value of c_account_info.old_address
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getOldAddress() {
        return oldAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.old_address
     *
     * @param oldAddress the value for c_account_info.old_address
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setOldAddress(String oldAddress) {
        this.oldAddress = oldAddress == null ? null : oldAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.village
     *
     * @return the value of c_account_info.village
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getVillage() {
        return village;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.village
     *
     * @param village the value for c_account_info.village
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setVillage(String village) {
        this.village = village == null ? null : village.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.car_brand
     *
     * @return the value of c_account_info.car_brand
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getCarBrand() {
        return carBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.car_brand
     *
     * @param carBrand the value for c_account_info.car_brand
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCarBrand(String carBrand) {
        this.carBrand = carBrand == null ? null : carBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.car_model
     *
     * @return the value of c_account_info.car_model
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getCarModel() {
        return carModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.car_model
     *
     * @param carModel the value for c_account_info.car_model
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCarModel(String carModel) {
        this.carModel = carModel == null ? null : carModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.sex
     *
     * @return the value of c_account_info.sex
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.sex
     *
     * @param sex the value for c_account_info.sex
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.bank_car_no
     *
     * @return the value of c_account_info.bank_car_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getBankCarNo() {
        return bankCarNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.bank_car_no
     *
     * @param bankCarNo the value for c_account_info.bank_car_no
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setBankCarNo(String bankCarNo) {
        this.bankCarNo = bankCarNo == null ? null : bankCarNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.open_bank
     *
     * @return the value of c_account_info.open_bank
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getOpenBank() {
        return openBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.open_bank
     *
     * @param openBank the value for c_account_info.open_bank
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setOpenBank(String openBank) {
        this.openBank = openBank == null ? null : openBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.info_from
     *
     * @return the value of c_account_info.info_from
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public String getInfoFrom() {
        return infoFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.info_from
     *
     * @param infoFrom the value for c_account_info.info_from
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setInfoFrom(String infoFrom) {
        this.infoFrom = infoFrom == null ? null : infoFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.net_car
     *
     * @return the value of c_account_info.net_car
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Integer getNetCar() {
        return netCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.net_car
     *
     * @param netCar the value for c_account_info.net_car
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setNetCar(Integer netCar) {
        this.netCar = netCar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.flag
     *
     * @return the value of c_account_info.flag
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.flag
     *
     * @param flag the value for c_account_info.flag
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.create_time
     *
     * @return the value of c_account_info.create_time
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.create_time
     *
     * @param createTime the value for c_account_info.create_time
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.update_time
     *
     * @return the value of c_account_info.update_time
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.update_time
     *
     * @param updateTime the value for c_account_info.update_time
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.lgt
     *
     * @return the value of c_account_info.lgt
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Double getLgt() {
        return lgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.lgt
     *
     * @param lgt the value for c_account_info.lgt
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setLgt(Double lgt) {
        this.lgt = lgt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_account_info.lat
     *
     * @return the value of c_account_info.lat
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public Double getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_account_info.lat
     *
     * @param lat the value for c_account_info.lat
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    public void setLat(Double lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_account_info
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CAccountInfo other = (CAccountInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
                && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
                && (this.getFatherId() == null ? other.getFatherId() == null : this.getFatherId().equals(other.getFatherId()))
                && (this.getGrandId() == null ? other.getGrandId() == null : this.getGrandId().equals(other.getGrandId()))
                && (this.getGgrandId() == null ? other.getGgrandId() == null : this.getGgrandId().equals(other.getGgrandId()))
                && (this.getMobileNo() == null ? other.getMobileNo() == null : this.getMobileNo().equals(other.getMobileNo()))
                && (this.getIdentityCard() == null ? other.getIdentityCard() == null : this.getIdentityCard().equals(other.getIdentityCard()))
                && (this.getDrivingCard() == null ? other.getDrivingCard() == null : this.getDrivingCard().equals(other.getDrivingCard()))
                && (this.getCarSideImg() == null ? other.getCarSideImg() == null : this.getCarSideImg().equals(other.getCarSideImg()))
                && (this.getCarHeaderImg() == null ? other.getCarHeaderImg() == null : this.getCarHeaderImg().equals(other.getCarHeaderImg()))
                && (this.getRealName() == null ? other.getRealName() == null : this.getRealName().equals(other.getRealName()))
                && (this.getIdentityNo() == null ? other.getIdentityNo() == null : this.getIdentityNo().equals(other.getIdentityNo()))
                && (this.getBorthDate() == null ? other.getBorthDate() == null : this.getBorthDate().equals(other.getBorthDate()))
                && (this.getPlateNo() == null ? other.getPlateNo() == null : this.getPlateNo().equals(other.getPlateNo()))
                && (this.getDetailAddress() == null ? other.getDetailAddress() == null : this.getDetailAddress().equals(other.getDetailAddress()))
                && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
                && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
                && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
                && (this.getProvinceCode() == null ? other.getProvinceCode() == null : this.getProvinceCode().equals(other.getProvinceCode()))
                && (this.getCityCode() == null ? other.getCityCode() == null : this.getCityCode().equals(other.getCityCode()))
                && (this.getAreaCode() == null ? other.getAreaCode() == null : this.getAreaCode().equals(other.getAreaCode()))
                && (this.getOldAddress() == null ? other.getOldAddress() == null : this.getOldAddress().equals(other.getOldAddress()))
                && (this.getVillage() == null ? other.getVillage() == null : this.getVillage().equals(other.getVillage()))
                && (this.getCarBrand() == null ? other.getCarBrand() == null : this.getCarBrand().equals(other.getCarBrand()))
                && (this.getCarModel() == null ? other.getCarModel() == null : this.getCarModel().equals(other.getCarModel()))
                && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
                && (this.getBankCarNo() == null ? other.getBankCarNo() == null : this.getBankCarNo().equals(other.getBankCarNo()))
                && (this.getOpenBank() == null ? other.getOpenBank() == null : this.getOpenBank().equals(other.getOpenBank()))
                && (this.getInfoFrom() == null ? other.getInfoFrom() == null : this.getInfoFrom().equals(other.getInfoFrom()))
                && (this.getNetCar() == null ? other.getNetCar() == null : this.getNetCar().equals(other.getNetCar()))
                && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
                && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
                && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
                && (this.getLgt() == null ? other.getLgt() == null : this.getLgt().equals(other.getLgt()))
                && (this.getLat() == null ? other.getLat() == null : this.getLat().equals(other.getLat()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_account_info
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getFatherId() == null) ? 0 : getFatherId().hashCode());
        result = prime * result + ((getGrandId() == null) ? 0 : getGrandId().hashCode());
        result = prime * result + ((getGgrandId() == null) ? 0 : getGgrandId().hashCode());
        result = prime * result + ((getMobileNo() == null) ? 0 : getMobileNo().hashCode());
        result = prime * result + ((getIdentityCard() == null) ? 0 : getIdentityCard().hashCode());
        result = prime * result + ((getDrivingCard() == null) ? 0 : getDrivingCard().hashCode());
        result = prime * result + ((getCarSideImg() == null) ? 0 : getCarSideImg().hashCode());
        result = prime * result + ((getCarHeaderImg() == null) ? 0 : getCarHeaderImg().hashCode());
        result = prime * result + ((getRealName() == null) ? 0 : getRealName().hashCode());
        result = prime * result + ((getIdentityNo() == null) ? 0 : getIdentityNo().hashCode());
        result = prime * result + ((getBorthDate() == null) ? 0 : getBorthDate().hashCode());
        result = prime * result + ((getPlateNo() == null) ? 0 : getPlateNo().hashCode());
        result = prime * result + ((getDetailAddress() == null) ? 0 : getDetailAddress().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getProvinceCode() == null) ? 0 : getProvinceCode().hashCode());
        result = prime * result + ((getCityCode() == null) ? 0 : getCityCode().hashCode());
        result = prime * result + ((getAreaCode() == null) ? 0 : getAreaCode().hashCode());
        result = prime * result + ((getOldAddress() == null) ? 0 : getOldAddress().hashCode());
        result = prime * result + ((getVillage() == null) ? 0 : getVillage().hashCode());
        result = prime * result + ((getCarBrand() == null) ? 0 : getCarBrand().hashCode());
        result = prime * result + ((getCarModel() == null) ? 0 : getCarModel().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getBankCarNo() == null) ? 0 : getBankCarNo().hashCode());
        result = prime * result + ((getOpenBank() == null) ? 0 : getOpenBank().hashCode());
        result = prime * result + ((getInfoFrom() == null) ? 0 : getInfoFrom().hashCode());
        result = prime * result + ((getNetCar() == null) ? 0 : getNetCar().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getLgt() == null) ? 0 : getLgt().hashCode());
        result = prime * result + ((getLat() == null) ? 0 : getLat().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_account_info
     *
     * @mbg.generated Tue May 15 22:44:53 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append(", fatherId=").append(fatherId);
        sb.append(", grandId=").append(grandId);
        sb.append(", ggrandId=").append(ggrandId);
        sb.append(", mobileNo=").append(mobileNo);
        sb.append(", identityCard=").append(identityCard);
        sb.append(", drivingCard=").append(drivingCard);
        sb.append(", carSideImg=").append(carSideImg);
        sb.append(", carHeaderImg=").append(carHeaderImg);
        sb.append(", realName=").append(realName);
        sb.append(", identityNo=").append(identityNo);
        sb.append(", borthDate=").append(borthDate);
        sb.append(", plateNo=").append(plateNo);
        sb.append(", detailAddress=").append(detailAddress);
        sb.append(", province=").append(province);
        sb.append(", city=").append(city);
        sb.append(", area=").append(area);
        sb.append(", provinceCode=").append(provinceCode);
        sb.append(", cityCode=").append(cityCode);
        sb.append(", areaCode=").append(areaCode);
        sb.append(", oldAddress=").append(oldAddress);
        sb.append(", village=").append(village);
        sb.append(", carBrand=").append(carBrand);
        sb.append(", carModel=").append(carModel);
        sb.append(", sex=").append(sex);
        sb.append(", bankCarNo=").append(bankCarNo);
        sb.append(", openBank=").append(openBank);
        sb.append(", infoFrom=").append(infoFrom);
        sb.append(", netCar=").append(netCar);
        sb.append(", flag=").append(flag);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", lgt=").append(lgt);
        sb.append(", lat=").append(lat);
        sb.append("]");
        return sb.toString();
    }


    public String getCarVideo() {
        return carVideo;
    }

    public void setCarVideo(String carVideo) {
        this.carVideo = carVideo;
    }

    @ApiModelProperty(value = "头衔地址", example = "zhangqw", position = 35, required = true)
    private String headImg;

    public String getHeadImg() {
        return headImg;
    }

    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }
}
