package com.cloud.carads.system.dictionary.entity;

import java.util.Date;

public class TdictionaryAttr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.id
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.dic_code
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private String dicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.attr_code
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private String attrCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.attr_value
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private String attrValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.attr_desc
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private String attrDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.crate_time
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private Date crateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.update_time
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary_attr.flag
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.id
     *
     * @return the value of t_dictionary_attr.id
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.id
     *
     * @param id the value for t_dictionary_attr.id
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.dic_code
     *
     * @return the value of t_dictionary_attr.dic_code
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.dic_code
     *
     * @param dicCode the value for t_dictionary_attr.dic_code
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.attr_code
     *
     * @return the value of t_dictionary_attr.attr_code
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public String getAttrCode() {
        return attrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.attr_code
     *
     * @param attrCode the value for t_dictionary_attr.attr_code
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setAttrCode(String attrCode) {
        this.attrCode = attrCode == null ? null : attrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.attr_value
     *
     * @return the value of t_dictionary_attr.attr_value
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.attr_value
     *
     * @param attrValue the value for t_dictionary_attr.attr_value
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.attr_desc
     *
     * @return the value of t_dictionary_attr.attr_desc
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public String getAttrDesc() {
        return attrDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.attr_desc
     *
     * @param attrDesc the value for t_dictionary_attr.attr_desc
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setAttrDesc(String attrDesc) {
        this.attrDesc = attrDesc == null ? null : attrDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.crate_time
     *
     * @return the value of t_dictionary_attr.crate_time
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public Date getCrateTime() {
        return crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.crate_time
     *
     * @param crateTime the value for t_dictionary_attr.crate_time
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setCrateTime(Date crateTime) {
        this.crateTime = crateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.update_time
     *
     * @return the value of t_dictionary_attr.update_time
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.update_time
     *
     * @param updateTime the value for t_dictionary_attr.update_time
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary_attr.flag
     *
     * @return the value of t_dictionary_attr.flag
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary_attr.flag
     *
     * @param flag the value for t_dictionary_attr.flag
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TdictionaryAttr other = (TdictionaryAttr) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDicCode() == null ? other.getDicCode() == null : this.getDicCode().equals(other.getDicCode()))
            && (this.getAttrCode() == null ? other.getAttrCode() == null : this.getAttrCode().equals(other.getAttrCode()))
            && (this.getAttrValue() == null ? other.getAttrValue() == null : this.getAttrValue().equals(other.getAttrValue()))
            && (this.getAttrDesc() == null ? other.getAttrDesc() == null : this.getAttrDesc().equals(other.getAttrDesc()))
            && (this.getCrateTime() == null ? other.getCrateTime() == null : this.getCrateTime().equals(other.getCrateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDicCode() == null) ? 0 : getDicCode().hashCode());
        result = prime * result + ((getAttrCode() == null) ? 0 : getAttrCode().hashCode());
        result = prime * result + ((getAttrValue() == null) ? 0 : getAttrValue().hashCode());
        result = prime * result + ((getAttrDesc() == null) ? 0 : getAttrDesc().hashCode());
        result = prime * result + ((getCrateTime() == null) ? 0 : getCrateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dicCode=").append(dicCode);
        sb.append(", attrCode=").append(attrCode);
        sb.append(", attrValue=").append(attrValue);
        sb.append(", attrDesc=").append(attrDesc);
        sb.append(", crateTime=").append(crateTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", flag=").append(flag);
        sb.append("]");
        return sb.toString();
    }
}