package com.cloud.carads.system.dictionary.entity;

import java.util.Date;

public class Tdictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.dic_code
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    private String dicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.dic_desc
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    private String dicDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.create_time
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.update_time
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dictionary.flag
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.dic_code
     *
     * @return the value of t_dictionary.dic_code
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.dic_code
     *
     * @param dicCode the value for t_dictionary.dic_code
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.dic_desc
     *
     * @return the value of t_dictionary.dic_desc
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public String getDicDesc() {
        return dicDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.dic_desc
     *
     * @param dicDesc the value for t_dictionary.dic_desc
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public void setDicDesc(String dicDesc) {
        this.dicDesc = dicDesc == null ? null : dicDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.create_time
     *
     * @return the value of t_dictionary.create_time
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.create_time
     *
     * @param createTime the value for t_dictionary.create_time
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.update_time
     *
     * @return the value of t_dictionary.update_time
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.update_time
     *
     * @param updateTime the value for t_dictionary.update_time
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dictionary.flag
     *
     * @return the value of t_dictionary.flag
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dictionary.flag
     *
     * @param flag the value for t_dictionary.flag
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tdictionary other = (Tdictionary) that;
        return (this.getDicCode() == null ? other.getDicCode() == null : this.getDicCode().equals(other.getDicCode()))
            && (this.getDicDesc() == null ? other.getDicDesc() == null : this.getDicDesc().equals(other.getDicDesc()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDicCode() == null) ? 0 : getDicCode().hashCode());
        result = prime * result + ((getDicDesc() == null) ? 0 : getDicDesc().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary
     *
     * @mbg.generated Sun May 20 01:41:32 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dicCode=").append(dicCode);
        sb.append(", dicDesc=").append(dicDesc);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", flag=").append(flag);
        sb.append("]");
        return sb.toString();
    }
}