package com.cloud.carads.system.area.mapper;

import com.cloud.carads.system.area.entity.TAreainfo;
import com.cloud.carads.system.area.entity.TAreainfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TAreainfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    long countByExample(TAreainfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int deleteByExample(TAreainfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int insert(TAreainfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int insertSelective(TAreainfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    List<TAreainfo> selectByExample(TAreainfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    TAreainfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") TAreainfo record, @Param("example") TAreainfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int updateByExample(@Param("record") TAreainfo record, @Param("example") TAreainfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int updateByPrimaryKeySelective(TAreainfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_d_areainfo
     *
     * @mbg.generated Sun May 20 01:32:48 CST 2018
     */
    int updateByPrimaryKey(TAreainfo record);
}