package com.cloud.carads.system.sms.mapper;

import com.cloud.carads.system.sms.entity.SmsLog;
import com.cloud.carads.system.sms.entity.SmsLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SmsLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    long countByExample(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int deleteByExample(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int insert(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int insertSelective(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    List<SmsLog> selectByExample(SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    SmsLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") SmsLog record, @Param("example") SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int updateByExample(@Param("record") SmsLog record, @Param("example") SmsLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int updateByPrimaryKeySelective(SmsLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sms_log
     *
     * @mbg.generated Sun May 20 01:44:42 CST 2018
     */
    int updateByPrimaryKey(SmsLog record);
}