package com.cloud.carads.capp.mapper;

import com.cloud.carads.capp.entity.CAppVersion;
import com.cloud.carads.capp.entity.CAppVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CAppVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    long countByExample(CAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int deleteByExample(CAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int insert(CAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int insertSelective(CAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    List<CAppVersion> selectByExample(CAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    CAppVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") CAppVersion record, @Param("example") CAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int updateByExample(@Param("record") CAppVersion record, @Param("example") CAppVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int updateByPrimaryKeySelective(CAppVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_app_version
     *
     * @mbg.generated Sun May 13 23:59:06 CST 2018
     */
    int updateByPrimaryKey(CAppVersion record);
}