package com.cloud.carads.system.carbarnd.mapper;

import com.cloud.carads.system.carbarnd.entity.CarBrandInfo;
import com.cloud.carads.system.carbarnd.entity.CarBrandInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarBrandInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    long countByExample(CarBrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int deleteByExample(CarBrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int deleteByPrimaryKey(String modelCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int insert(CarBrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int insertSelective(CarBrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    List<CarBrandInfo> selectByExample(CarBrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    CarBrandInfo selectByPrimaryKey(String modelCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") CarBrandInfo record, @Param("example") CarBrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int updateByExample(@Param("record") CarBrandInfo record, @Param("example") CarBrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int updateByPrimaryKeySelective(CarBrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    int updateByPrimaryKey(CarBrandInfo record);
}