package com.cloud.carads.system.dictionary.mapper;

import com.cloud.carads.system.dictionary.entity.TdictionaryAttr;
import com.cloud.carads.system.dictionary.entity.TdictionaryAttrExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TdictionaryAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    long countByExample(TdictionaryAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int deleteByExample(TdictionaryAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int insert(TdictionaryAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int insertSelective(TdictionaryAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    List<TdictionaryAttr> selectByExample(TdictionaryAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    TdictionaryAttr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") TdictionaryAttr record, @Param("example") TdictionaryAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int updateByExample(@Param("record") TdictionaryAttr record, @Param("example") TdictionaryAttrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int updateByPrimaryKeySelective(TdictionaryAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_dictionary_attr
     *
     * @mbg.generated Sun May 20 01:42:44 CST 2018
     */
    int updateByPrimaryKey(TdictionaryAttr record);
}