package com.cloud.carads.system.carbarnd.entity;

public class CarBrandInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brandinfo.model_code
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    private String modelCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brandinfo.model_name
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brandinfo.level
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brandinfo.parent_code
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    private String parentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brandinfo.flag
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    private Integer flag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_brandinfo.in_level
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    private Integer inLevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brandinfo.model_code
     *
     * @return the value of t_car_brandinfo.model_code
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brandinfo.model_code
     *
     * @param modelCode the value for t_car_brandinfo.model_code
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode == null ? null : modelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brandinfo.model_name
     *
     * @return the value of t_car_brandinfo.model_name
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brandinfo.model_name
     *
     * @param modelName the value for t_car_brandinfo.model_name
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brandinfo.level
     *
     * @return the value of t_car_brandinfo.level
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brandinfo.level
     *
     * @param level the value for t_car_brandinfo.level
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brandinfo.parent_code
     *
     * @return the value of t_car_brandinfo.parent_code
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brandinfo.parent_code
     *
     * @param parentCode the value for t_car_brandinfo.parent_code
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brandinfo.flag
     *
     * @return the value of t_car_brandinfo.flag
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brandinfo.flag
     *
     * @param flag the value for t_car_brandinfo.flag
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_car_brandinfo.in_level
     *
     * @return the value of t_car_brandinfo.in_level
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public Integer getInLevel() {
        return inLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_car_brandinfo.in_level
     *
     * @param inLevel the value for t_car_brandinfo.in_level
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    public void setInLevel(Integer inLevel) {
        this.inLevel = inLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CarBrandInfo other = (CarBrandInfo) that;
        return (this.getModelCode() == null ? other.getModelCode() == null : this.getModelCode().equals(other.getModelCode()))
            && (this.getModelName() == null ? other.getModelName() == null : this.getModelName().equals(other.getModelName()))
            && (this.getLevel() == null ? other.getLevel() == null : this.getLevel().equals(other.getLevel()))
            && (this.getParentCode() == null ? other.getParentCode() == null : this.getParentCode().equals(other.getParentCode()))
            && (this.getFlag() == null ? other.getFlag() == null : this.getFlag().equals(other.getFlag()))
            && (this.getInLevel() == null ? other.getInLevel() == null : this.getInLevel().equals(other.getInLevel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getModelCode() == null) ? 0 : getModelCode().hashCode());
        result = prime * result + ((getModelName() == null) ? 0 : getModelName().hashCode());
        result = prime * result + ((getLevel() == null) ? 0 : getLevel().hashCode());
        result = prime * result + ((getParentCode() == null) ? 0 : getParentCode().hashCode());
        result = prime * result + ((getFlag() == null) ? 0 : getFlag().hashCode());
        result = prime * result + ((getInLevel() == null) ? 0 : getInLevel().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_brandinfo
     *
     * @mbg.generated Wed May 23 23:55:30 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", modelCode=").append(modelCode);
        sb.append(", modelName=").append(modelName);
        sb.append(", level=").append(level);
        sb.append(", parentCode=").append(parentCode);
        sb.append(", flag=").append(flag);
        sb.append(", inLevel=").append(inLevel);
        sb.append("]");
        return sb.toString();
    }
}